sources:
  - name: raw
    schema: Electronics_Retailer 
    tables:
      - name: Sales
      - name: Products
      - name: Exchange_rates
      - name: Customers
      - name: Stores
models:
  - name: stg_sales
    description: "sales data"
    columns:
      - name: order_number
        tests: [not_null]
      - name: product_key
        tests:
          - not_null
          - relationships:
              to: ref('stg_products')
              field: product_key
      - name: currency_code
        tests:
          - accepted_values:
              values: ['USD', 'CAD', 'AUD', 'EUR', 'GBP']

  - name: stg_products
    description: "Cleaned product data"
    columns:
      - name: product_key
        tests: [unique, not_null]
      - name: unit_cost_usd
        tests: [not_null]

  - name: stg_exchange_rates
    description: "Exchange rates per currency-date"
    columns:
      - name: currency
        tests: [not_null]
      - name: date
        tests: [not_null]

  - name: stg_customers
    description: "Cleaned customer data"
    columns:
      - name: customer_key
        tests: [unique, not_null]

  - name: stg_stores
    description: "Store metadata"
    columns:
      - name: store_key
        tests: [unique, not_null]
