models:
  - name: mart_sales_by_date
    description: "Daily sales KPIs, for example AOV."
    columns:
      - name: order_date
        tests: [not_null]
      - name:  avg_order_value
        tests: [not_null]

  - name: mart_customer_segments
    description: "Customers with tenure and LTV."
    columns:
      - name: customer_key
        tests: [not_null, unique]
      - name: customer_type
        tests:
            - accepted_values:
                values: ['One-time', 'Returning', 'No Orders']
      - name: customer_tenure_days
        tests:
            - not_null

  - name: mart_brand_performance
    description: "Brands revenue, margin and performance per day."
    columns:
      - name: brand
        tests: [not_null]
      - name: avg_profit_margin
        tests:
            - not_null

  - name: mart_churn_eval
    description: "Churn evaluation"
    columns:
      - name: customer_key
        tests: [not_null]
      - name: is_churned
        tests:
          - accepted_values:
              values: [1, 0]